#!/bin/bash
ls -l 3-listfies total 20 -rwxr--r-- 1 root root 70 May 26 19:45 0-current_working_directory  -rwxr-xr-x 1 root root 62 May 26 20:53 1-listit                             -rwxr--r-- 1 root root 21 May 26 21:44 2-bring_me_home              -rwxr--r-- 1 root root 13 May 27 00:57 3-listfiles 
